services:
  - type: web
    name: sanitarico-website
    runtime: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./out
    pullRequestPreviewsEnabled: true
    headers:
      - path: "/*"
        name: X-Frame-Options
        value: DENY
      - path: "/*"
        name: X-Content-Type-Options
        value: nosniff
      - path: "/*"
        name: Referrer-Policy
        value: strict-origin-when-cross-origin
